### ISSUE TITLE
Using Clustered ONTAP with FCP or iSCSI requires mpio in linux, but prio should be "alua" with more than one storage node, not "ontap"

### ISSUE THREAD

**Issue by oleimann** [NetAppDocs/ontap-sanhost#19]
Page: [Using Red Hat Enterprise Linux 7.5 with NetApp ONTAP](https://docs.netapp.com/us-en/ontap-sanhost/hu_rhel_75.html)

This is the case for every Linux Host with Clustered ONTAP that already has alua support in the mpio drivers.
See Host Utilities 7.1 documentation:
https://library.netapp.com/ecm/ecm_download_file/ECMLP2547957

Note that only for single node storage clusters, the priority as alua doesn't make sense, since alua sets priority by primary or secondary (partner) path. 
Note: only very old QLogic drivers or Host Utilities 4.1 still have the ontap prioritizer script with them.

**Comment by netapp-ranuk** [comment]
Thanks for your comment. We are investigating this.

**Comment by netapp-ranuk** [comment]
The link mentioned in the comment https://library.netapp.com/ecm/ecm_download_file/ECMLP2547957 is an old version. We suggest referring to our new version of the Linux Host Utilities https://docs.netapp.com/us-en/ontap-sanhost/hu_luhu_71.html.

Additionally, the setting {prio "ontap"} mentioned in the new RHEL 7.5 GitHub page is the correct one. Since we are also setting {detect_prio “yes’}, the multipathd will detect the correct “prio” during NETAP LUN discovery.

Please let us know if you've any further concerns. Thank you.
