### ISSUE TITLE
Improvement idea regarding multipath.conf 

### ISSUE THREAD

**Issue by rovandep** [NetAppDocs/ontap-sanhost#30]
Page: [Using Red Hat Enterprise Linux 7.9 with NetApp ONTAP](https://docs.netapp.com/us-en/ontap-sanhost/hu_rhel_79.html)

The parameters table is really nice but a bit confusing if the reader doesn't know exactly in which sections of the multipath.conf they should go in. It would be nice if this table would be broken down  based on the "defaults" and "device" sections of the multipath.conf configuration file. 
Also, if not mistaken, there was clear multipath.conf example per OS versions in previous versions of the documentation.

Thanks for your great job with the documentation;)

**Comment by netapp-ranuk** [comment]
Thanks for your suggestion. We are looking into this.

**Comment by netapp-ranuk** [comment]
We have not mentioned the different sections “multipath.conf” file since for new OSes like RHEL 7.x and RHEL 8.x, the content of multipath.conf file should be blank for NETAPP LUNs, except if user wants to add any “blacklist” section. This was deliberately done to avoid confusion. In the earlier versions of the docs, we had mentioned different sections of “multipath.conf” file because for older RHEL OSes (RHEL 5.x, RHEL 6.0 to 6.4) user had to specifically add those sections and values manually into “multipath.conf” file. But for new RHEL OSes, this is not required. And hence we have not mentioned it. Please contact us if you've any further concerns. Thank you.
