### ISSUE TITLE
The table below shows the critical multipathd parameters for ONTAP LUNs and the required values

### ISSUE THREAD

**Issue by Brandon12345678901** [NetAppDocs/ontap-sanhost#68]
Page: [Using Oracle Linux 7.8 with NetApp ONTAP](https://docs.netapp.com/us-en/ontap-sanhost/hu_ol_78.html)

Hi can we update the document, the settings in this table are not correct for ALUA as far as I can tell , which is required for Clustered ONTAP. 

"The table below shows the critical multipathd parameters for ONTAP LUNs and the required values." 
hardware_handler "0"
prio "ontap"

This should only be used is ALUA is not supported as far as I can tell. 

The parameters should be 
hardware_handler "1 alua"
prio "alua"

https://library.netapp.com/ecmdocs/ECMP1217221/html/GUID-C5CFA561-7FD1-45F2-8BF8-1C7F04910274.html

**Comment by lescar** [comment]
Discussed a similar topic yesterday and like to share my findings: hardware_handler 0 gets ignored due to: retain_attached_hw_handler yes as documented. The multipath -ll output confirms this as well and it's documented at least in our Redhat parts of the documentation: https://docs.netapp.com/us-en/ontap-sanhost/hu_rhel_78.html#recommended-settings

retain_attached_hw_handler: If this parameter is set to yes and the SCSI layer has already attached a hardware handler to the path device, multipath will not force the device to use the hardware_handler specified by the multipath.conf file. If the SCSI layer has not attached a hardware handler, multipath will continue to use its configured hardware handler as usual. The default value is no.
- Source: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html-single/dm_multipath/index

I hope this helps.

**Comment by netapp-ranuk** [comment]
Hi @Brandon12345678901 Thanks for reaching out. Our recommendation is to provide empty multipath.conf in our documentation unless there's a need to override any specific multipath parameter explicitly. Please let us know if you've further concerns.
